#include <cmath>
#include <fstream>
#include <iostream>
#include <mutex>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include "docopt.h"
#include "particle.h"

using namespace std;

static char USAGE[] = R"(
This Routine is used to Check the simulation of one particle.

    Usage:
      ./ParticleTest [options] <outfile>

    Options:
      -h --help                         Show this help.
      -s SEED, --seed SEED              The global seed of this routine, it would be automatically given if not assigned.
      -A A, --A A                       The nucleon number A of particle [default: 1].
      -Z Z, --Z Z                       The charge number Z of particle [default: 1].
      -B B0, --B0 B0                    The magnetic strength around the Earth in nT [default: 5].
      -p POLARITY, --polarity POLARITY  The direction polarity of the magnetic field [default: -1].
      -a ANGLE, --angle ANGLE           Tilt angle of HCS in deg [default: 15].
      --hcs-osc-amp AMP                 HCS tilt perturbation amplitude in deg [default: 0].
      --hcs-osc-phase PHASE             HCS tilt perturbation phase in deg [default: 0].
      --hcs-omega OMEGA                 HCS tilt perturbation angular frequency in units of HCS::Omega [default: 1].
      -D D0, --D0 D0                    Reference diffusion coefficient in unit 1e22 cm^2/s [default: 5].
      -R R0, --R0 R0                    Reference rigidity for the diffusion coefficient in unit GV [default: 1].
      --max-step MSTEP                  The maximum allowed steps [default: -1].
      --hcs-table HCS_TABLE             If the dir of the table generated by gen_HCS_distance_map given, to interpolate the HCS distance with it [default: ""].
      --m M                             Co-rotation factor in azimuthal drift [default: 0].
      --indexA INDEXA                   Diffusion index a [default: 1].
      --indexB INDEXB                   Diffusion index b [default: 1].
      --ekin EKINS                      The ekin of particle [default: 0.5].
)";
int main(int argc, char* argv[]) {
  std::map<std::string, docopt::value> args = docopt::docopt(USAGE, {argv + 1, argv + argc}, true);
  auto fargs = [&](const string& k) { return atof(args.at(k).asString().c_str()); };

  HCS::angle = stod(args.at("--angle").asString()) * Unit::deg;
  HCS::angle_osc_amp = stod(args.at("--hcs-osc-amp").asString()) * Unit::deg;
  HCS::angle_osc_phase = stod(args.at("--hcs-osc-phase").asString()) * Unit::deg;
  HCS::hcs_omega = stod(args.at("--hcs-omega").asString()) * HCS::Omega;
  HCS::hcsform = HCS::Kota_Jokipii;

  particle one(args);
  one.Ek = fargs("--ekin") * Unit::GeV;
  one.fix_seed = bool(args.at("--seed"));
  one.seed = one.fix_seed ? args.at("--seed").asLong() : 0;
  one.step(args.at("<outfile>").asString(), args.at("--max-step").asLong());

  return 0;
}
